name       : python-setuptools-scm
version    : 1.15.0
release    : 1
source     :
    - https://pypi.python.org/packages/80/b7/31b6ae5fcb188e37f7e31abe75f9be90490a5456a72860fa6e643f8a3cbc/setuptools_scm-1.15.0.tar.gz : daf12d05aa2155a46aa357453757ffdc47d87f839e62114f042bceac6a619e2f
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of
    declaring them as the version argument or in a scm managed file.
    It also handles file finders for the supported scm.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
