name       : python-setuptools-scm
version    : 1.15.6
release    : 2
source     :
    - https://pypi.python.org/packages/03/6d/aafdd01edd227ee879b691455bf19895091872af7e48192bea1758c82032/setuptools_scm-1.15.6.tar.gz : 49ab4685589986a42da85706b3311a2f74f1af567d39fee6cb1e088d7a75fb5f
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of
    declaring them as the version argument or in a scm managed file.
    It also handles file finders for the supported scm.
builddeps  :
    - git           # check
    - mercurial     # check
    - pip           # check
    - python-pytest # check
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$installdir/usr/lib/python2.7/site-packages py.test -v
    popd
    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$installdir/usr/lib/python3.5/site-packages py.test3 -v
    popd
