name       : python-setuptools-scm
version    : 3.1.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/s/setuptools_scm/setuptools_scm-3.1.0.tar.gz : 1191f2a136b5e86f7ca8ab00a97ef7aef997131f1f6d4971be69a1ef387d8b40
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of
    declaring them as the version argument or in a scm managed file.
    It also handles file finders for the supported scm.
builddeps  :
    - git           # check
    - mercurial     # check
    - pip           # check
    - python-pytest # check
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        pyVer=$(python --version 2>&1 | sed -r 's|^Python (.*)\..*$|\1|')
        PYTHONPATH=$installdir/usr/lib/python${pyVer}/site-packages py.test -v -k 'not (test_pip_download or test_old_setuptools_fails or test_old_setuptools_allows_with_warnings or test_distlib_setuptools_works)'
    popd
    pushd $PKG_BUILD_DIR/py3build
        pyVer=$(python3 --version 2>&1 | sed -r 's|^Python (.*)\..*$|\1|')
        PYTHONPATH=$installdir/usr/lib/python${pyVer}/site-packages py.test3 -v -k 'not (test_pip_download or test_old_setuptools_fails or test_old_setuptools_allows_with_warnings or test_distlib_setuptools_works)'
    popd
