name       : python-setuptools-scm
version    : 5.0.2
release    : 17
source     :
    - https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-5.0.2.tar.gz : 83a0cedd3449e3946307811a4c7b9d89c4b5fd464a2fb5eeccd0a5bb158ae5c8
homepage   : https://github.com/pypa/setuptools_scm/
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of declaring them as the version argument or in a scm managed file. It also handles file finders for the supported scm.
builddeps  :
    - git           # check
    - mercurial     # check
    - python-pytest # check
    - python-tomli  # check
rundeps    :
    - python-packaging
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test py.test3 -v -k 'not (test_pip_download or test_integration)'
