name       : python-setuptools-scm
version    : 3.3.3
release    : 6
source     :
    - https://files.pythonhosted.org/packages/83/44/53cad68ce686585d12222e6769682c4bdb9686808d2739671f9175e2938b/setuptools_scm-3.3.3.tar.gz : bd25e1fb5e4d603dcf490f1fde40fb4c595b357795674c3e5cb7f6217ab39ea5
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of
    declaring them as the version argument or in a scm managed file.
    It also handles file finders for the supported scm.
builddeps  :
    - git           # check
    - mercurial     # check
    - pip           # check
    - python-pytest # check
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    pushd $PKG_BUILD_DIR/py2build
#        pyVer=$(python --version 2>&1 | sed -r 's|^Python (.*)\..*$|\1|')
#        PYTHONPATH=$installdir/usr/lib/python${pyVer}/site-packages py.test -v -k 'not (test_pip_download or test_old_setuptools_fails or test_old_setuptools_allows_with_warnings or test_distlib_setuptools_works)'
#    popd
#    pushd $PKG_BUILD_DIR/py3build
#        pyVer=$(python3 --version 2>&1 | sed -r 's|^Python (.*)\..*$|\1|')
#        PYTHONPATH=$installdir/usr/lib/python${pyVer}/site-packages py.test3 -v -k 'not (test_pip_download or test_old_setuptools_fails or test_old_setuptools_allows_with_warnings or test_distlib_setuptools_works)'
#    popd
