name       : python-setuptools-scm
version    : 6.4.2
release    : 15
source     :
    - https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-6.4.2.tar.gz : 6833ac65c6ed9711a4d5d2266f8024cfa07c533a0e55f4c12f6eff280a5a9e30
homepage   : https://github.com/pypa/setuptools_scm/
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of declaring them as the version argument or in a scm managed file. It also handles file finders for the supported scm.
builddeps  :
    - git           # check
    - mercurial     # check
    - python-pytest # check
    - python-tomli  # check
rundeps    :
    - python-packaging
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v -k 'not (test_pip_download or test_integration)'
