name       : python-setuptools-scm
version    : 4.1.2
release    : 7
source     :
    - https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-4.1.2.tar.gz : a8994582e716ec690f33fec70cca0f85bd23ec974e3f783233e4879090a7faa8
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of declaring them as the version argument or in a scm managed file.
    It also handles file finders for the supported scm.
builddeps  :
    - git           # check
    - mercurial     # check
    - pip           # check
    - python-pytest # check
    - python-setuptools
    - python-toml   # check
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v -k 'not (test_pip_download or test_setuptools_support or test_integration)'
    %python3_test py.test3 -v -k 'not (test_pip_download or test_integration)'
