name       : python-setuptools-scm
version    : 5.0.1
release    : 10
source     :
    - https://pypi.io/packages/source/s/setuptools_scm/setuptools_scm-5.0.1.tar.gz : c85b6b46d0edd40d2301038cdea96bb6adc14d62ef943e75afb08b3e7bcf142a
license    : MIT
component  : programming.python
summary    : Manage your Python package versions using scm metadata
description: |
    setuptools_scm handles managing your Python package versions in scm metadata instead of declaring them as the version argument or in a scm managed file.
    It also handles file finders for the supported scm.
builddeps  :
    - git           # check
    - mercurial     # check
    - pip           # check
    - python-pytest # check
    - python-setuptools
    - python-toml   # check
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test -v -k 'not (test_pip_download or test_setuptools_support or test_integration)'
    %python3_test py.test3 -v -k 'not (test_pip_download or test_integration)'
